<select id="propinsi" class="form-control required" name="propinsi" >
      <option value="">--</option>
      <option value="NanggroeAcehDarussalam">Nanggroe Aceh Darussalam</option>
      <option value="SumateraUtara">Sumatera Utara</option>
      <option value="SumateraBarat">Sumatera Barat</option>
      <option value="Bengkulu">Bengkulu</option>
      <option value="Jambi">Jambi</option>
      <option value="Riau">Riau</option>
      <option value="SumateraSelatan">Sumatera Selatan</option>
      <option value="Lampung">Lampung</option>
      <option value="KepulauanBangkaBelitung">Kepulauan Bangka Belitung</option>
      <option value="KepulauanRiau">Kepulauan Riau</option>
      <option value="Banten">Banten</option>
      <option value="DKIJakarta">DKI Jakarta</option>
      <option value="JawaBarat">Jawa Barat</option>
      <option value="JawaTengah">Jawa Tengah</option>
      <option value="JawaTimur">Jawa Timur</option>
      <option value="DIYogyakarta">DI Yogyakarta</option>
      <option value="Bali">Bali</option>
      <option value="NusaTenggaraBarat">Nusa Tenggara Barat</option>
      <option value="NusaTenggaraTimur">Nusa Tenggara Timur</option>
      <option value="KalimantanBarat">Kalimantan Barat</option>
      <option value="KalimantanSelatan">Kalimantan Selatan</option>
      <option value="KalimantanTengah">Kalimantan Tengah</option>
      <option value="KalimantanTimur">Kalimantan Timur</option>
      <option value="KalimantanUtara">Kalimantan Utara</option>
      <option value="Gorontalo">Gorontalo</option>
      <option value="SulawesiSelatan">Sulawesi Selatan</option>
      <option value="SulawesiTenggara">Sulawesi Tenggara</option>
      <option value="SulawesiTengah">Sulawesi Tengah</option>
      <option value="SulawesiUtara">Sulawesi Utara</option>
      <option value="SulawesiBarat">Sulawesi Barat</option>
      <option value="Maluku">Maluku</option>
      <option value="MalukuUtara">Maluku Utara</option>
      <option value="PapuaBarat">Papua Barat</option>
      <option value="Papua">Papua</option>
      <option value="TelukCenderawasih">Teluk Cenderawasih</option>
</select>